name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Matches semantic versioning tags like v1.0.0
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [Debug, Release]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for GitVersion
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Install OpenAL and PulseAudio dependencies on Linux
    - name: Install Linux Audio Dependencies
      if: runner.os == 'Linux'
      run: |
        # Install audio dependencies
        sudo apt-get update
        # Install audio dependencies
        sudo apt-get install -y libopenal1
        sudo apt-get install -y --no-install-recommends \
          libopenal1 \
          libopenal-data \
          alsa-utils \
          pulseaudio \
          pulseaudio-utils \
          pavucontrol \
          libasound2-plugins \
          alsa-oss \
          dbus \
          psmisc
        
        # Stop any existing PulseAudio processes
        sudo killall pulseaudio || true
        sudo killall -9 pulseaudio || true
        
        # Create pulse user and group if they don't exist
        sudo groupadd -f pulse
        sudo groupadd -f pulse-access
        sudo useradd -g pulse -G audio,pulse-access -d /var/run/pulse pulse || true
        
        # Create and set permissions for PulseAudio directories
        sudo mkdir -p /var/run/pulse /var/lib/pulse /run/pulse
        sudo mkdir -p /var/run/pulse/.config/pulse
        sudo mkdir -p /etc/pulse /etc/openal
        
        # Set proper ownership and permissions
        sudo chown -R pulse:pulse /var/run/pulse /var/lib/pulse /run/pulse
        sudo chmod -R 755 /var/run/pulse /var/lib/pulse /run/pulse
        sudo chown -R pulse:pulse /var/run/pulse/.config
        sudo chmod -R 700 /var/run/pulse/.config
        
        # Setup D-Bus
        sudo mkdir -p /run/dbus
        sudo dbus-uuidgen --ensure
        sudo dbus-daemon --system --fork
        
        # Set runtime directory
        export XDG_RUNTIME_DIR=/run/pulse
        sudo -u pulse mkdir -p $XDG_RUNTIME_DIR
        sudo chmod 700 $XDG_RUNTIME_DIR
        sudo chown pulse:pulse $XDG_RUNTIME_DIR
        
        # Create PulseAudio configuration files as root first
        sudo tee /etc/pulse/system.pa > /dev/null << 'EOFPA'
        .fail
        .nofail
        
        load-module module-device-restore
        load-module module-stream-restore
        load-module module-card-restore
        
        load-module module-augment-properties
        load-module module-switch-on-port-available
        
        load-module module-native-protocol-unix auth-anonymous=1
        
        load-module module-null-sink sink_name=DummyOutput channels=2 channel_map=front-left,front-right rate=44100 format=float32le
        load-module module-always-sink
        
        set-default-sink DummyOutput
        EOFPA
        
        sudo tee /etc/pulse/client.conf > /dev/null << 'EOFCLIENT'
        default-server = unix:/run/pulse/native
        autospawn = no
        daemon-binary = /bin/true
        enable-shm = yes
        EOFCLIENT
        
        sudo tee /etc/pulse/daemon.conf > /dev/null << 'EOFDAEMON'
        daemonize = no
        system-instance = yes
        exit-idle-time = -1
        allow-module-loading = yes
        allow-exit = yes
        enable-shm = yes
        enable-memfd = yes
        flat-volumes = no
        default-sample-format = float32le
        default-sample-rate = 44100
        default-sample-channels = 2
        default-channel-map = front-left,front-right
        EOFDAEMON
        
        sudo tee /etc/openal/alsoft.conf > /dev/null << 'EOFAL'
        drivers=pulse
        [pulse]
        allow-moves=true
        default=true
        channels=stereo
        [general]
        channels=stereo
        frequency=44100
        samples=4096
        debug-level=4
        disable-denormals=true
        cf_level=2
        rt-prio=0
        period_size=1024
        periods=4
        EOFAL
        
        sudo tee /etc/asound.conf > /dev/null << 'EOFALSA'
        pcm.!default {
            type pulse
        }
        
        ctl.!default {
            type pulse
        }
        EOFALSA

        # Fix permissions on all config files
        sudo chown -R pulse:pulse /etc/pulse
        sudo chmod 755 /etc/pulse
        sudo chmod 644 /etc/pulse/*
        sudo chown -R pulse:pulse /etc/openal
        sudo chmod 755 /etc/openal
        sudo chmod 644 /etc/openal/*
        sudo chown pulse:pulse /etc/asound.conf
        sudo chmod 644 /etc/asound.conf
        
        # Create cookie file
        sudo -u pulse touch /var/run/pulse/.config/pulse/cookie
        sudo chmod 600 /var/run/pulse/.config/pulse/cookie

    # Start PulseAudio in system mode
    - name: Start PulseAudio
      if: runner.os == 'Linux'
      run: |
        # Export runtime directory for pulse user
        export XDG_RUNTIME_DIR=/run/pulse
        
        # Start PulseAudio as pulse user
        sudo -u pulse XDG_RUNTIME_DIR=/run/pulse HOME=/var/run/pulse pulseaudio --system --disallow-exit --disallow-module-loading --exit-idle-time=-1 --log-level=4 &
        sleep 5  # Give time for PulseAudio to start
        
        # Verify PulseAudio is running and show debug info
        sudo -u pulse XDG_RUNTIME_DIR=/run/pulse HOME=/var/run/pulse pulseaudio --check
        sudo -u pulse XDG_RUNTIME_DIR=/run/pulse HOME=/var/run/pulse pactl info || true
        sudo -u pulse XDG_RUNTIME_DIR=/run/pulse HOME=/var/run/pulse pactl list sinks || true
        sudo -u pulse XDG_RUNTIME_DIR=/run/pulse HOME=/var/run/pulse pactl list short || true
        sudo -u pulse XDG_RUNTIME_DIR=/run/pulse HOME=/var/run/pulse aplay -l || true
        sudo -u pulse XDG_RUNTIME_DIR=/run/pulse HOME=/var/run/pulse cat /proc/asound/cards || true
        sudo -u pulse XDG_RUNTIME_DIR=/run/pulse HOME=/var/run/pulse openal-info || true
        
        # Set OpenAL environment variables
        echo "ALSOFT_DRIVERS=pulse" >> $GITHUB_ENV
        echo "ALSOFT_LOGLEVEL=4" >> $GITHUB_ENV
        echo "ALSOFT_LOGFILE=/tmp/openal.log" >> $GITHUB_ENV

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
      
    - name: Test
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal
        else
          # Set OpenAL environment variables
          export ALSOFT_DRIVERS=pulse
          export ALSOFT_LOGLEVEL=4
          export ALSOFT_LOGFILE=/tmp/openal.log
          export XDG_RUNTIME_DIR=/run/pulse
          export HOME=/var/run/pulse
          
          # Get the current PATH and .NET paths
          CURRENT_PATH=$PATH
          DOTNET_PATH=$(which dotnet)
          DOTNET_ROOT=$(dirname $(readlink -f $(which dotnet)))
          
          # Run tests as pulse user to ensure proper audio access
          sudo -E -u pulse \
            PATH="$CURRENT_PATH" \
            XDG_RUNTIME_DIR=/run/pulse \
            HOME=/var/run/pulse \
            ALSOFT_DRIVERS=pulse \
            ALSOFT_LOGLEVEL=4 \
            ALSOFT_LOGFILE=/tmp/openal.log \
            DOTNET_ROOT="$DOTNET_ROOT" \
            "$DOTNET_PATH" test --configuration ${{ matrix.configuration }} --no-build --verbosity normal --filter "Category!=Platform_Specific"
          
          # Display OpenAL log if it exists
          if [ -f /tmp/openal.log ]; then
            echo "OpenAL Log:"
            cat /tmp/openal.log
          fi
        fi
      shell: bash
      
    # Package CLI tool (only on Release configuration)
    - name: Package CLI Tool
      if: matrix.configuration == 'Release'
      run: dotnet pack src/LofiBeats.Cli/LofiBeats.Cli.csproj --configuration Release --no-build --output nupkg
      
    # Upload artifacts
    - name: Upload NuGet Package
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package-${{ matrix.os }}
        path: nupkg/*.nupkg
        
    # Upload test results (if any test runners generate them)
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.configuration }}
        path: |
          **/TestResults/*.trx
          **/TestResults/*.xml

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    # Extract version from tag
    - name: Get Version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: nuget-package-*
        path: packages
        merge-multiple: true
        
    - name: Setup GitHub Packages
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: packages/*.nupkg
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish NuGet Package
      run: |
        for package in packages/*.nupkg; do
          dotnet nuget push "$package" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
        done
        
    - name: Publish to NuGet
      run: |
        for package in packages/*.nupkg; do
          dotnet nuget push "$package" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}
        done
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} 